font_family JetBrainsMono Nerd Font

cursor #d3c6aa
background_opacity 1.0

# === Поведение ===
visual_bell_duration 0
enable_audio_bell no

# === Работа с Wayland ===
linux_display_server wayland
wheel_scroll_multiplier 5.0
touch_scroll_multiplier 1.0

# === Клавиатура ===
map ctrl+left  send_text normal \x1bb
map ctrl+right send_text normal \x1bf
map ctrl+backspace send_text normal \x15

# === Полезные фишки ===
map ctrl+shift+u  open_url

# Сглаживание курсора
cursor_shape           beam
cursor_blink_interval  0
hide_window_decorations no
allow_remote_control yes
clipboard_control write-clipboard write-primary
map ctrl+shift+v paste_from_clipboard
map shift+insert paste_from_clipboard

# Тема Everforest
include ~/.config/kitty/everforest.conf
